import type { MenuItem, WorkingHours } from '@/types';

export const MENU_ITEMS: MenuItem[] = [
  // Coffee
  {
    id: 'espresso',
    name: 'Еспресо',
    nameEn: 'Espresso',
    description: 'Двоен шот от единичен произход. Интензивен, кадифен, с шоколадово послевкусие.',
    price: 2.5,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=600&q=80',
    featured: true,
    tags: ['класика', 'силно'],
  },
  {
    id: 'cappuccino',
    name: 'Капучино',
    nameEn: 'Cappuccino',
    description: 'Еспресо с пухкава микропяна от прясно пълномаслено мляко. Топъл, балансиран.',
    price: 4.0,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&q=80',
    featured: true,
    tags: ['мляко', 'класика'],
  },
  {
    id: 'flat-white',
    name: 'Флат Уайт',
    nameEn: 'Flat White',
    description: 'Ристрето с двойна порция финна текстурирана пара. Плътен и концентриран.',
    price: 4.5,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=600&q=80',
    featured: true,
    tags: ['specialty', 'силно'],
  },
  {
    id: 'pour-over',
    name: 'Пур Овър',
    nameEn: 'Pour Over',
    description: 'Ръчно преляно кафе. Цветни, сложни нотки в зависимост от произхода.',
    price: 6.0,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80',
    tags: ['filter', 'specialty'],
  },
  {
    id: 'cold-brew',
    name: 'Студена Напитка',
    nameEn: 'Cold Brew',
    description: '18-часово студено извличане. Гладко, леко сладко, без горчивина.',
    price: 5.5,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80',
    tags: ['студено', 'летен фаворит'],
  },
  {
    id: 'latte',
    name: 'Лате',
    nameEn: 'Latte',
    description: 'Еспресо с 180мл разпенено мляко. Мек, кремообразен, с деликатен кофеин.',
    price: 4.5,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1561882468-9110e03e0f78?w=600&q=80',
    tags: ['мляко', 'мек'],
  },
  // Desserts
  {
    id: 'tiramisu',
    name: 'Тирамису',
    nameEn: 'Tiramisu',
    description: 'Класическо италианско тирамису с маскарпоне, савоярди и двоен еспресо.',
    price: 7.0,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80',
    featured: true,
    tags: ['италианско', 'класика'],
  },
  {
    id: 'cheesecake',
    name: 'Чийзкейк',
    nameEn: 'Cheesecake',
    description: 'Нюйоркски чийзкейк с малинов кули и хрупкава бисквитена основа.',
    price: 6.5,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=600&q=80',
    tags: ['плодов', 'свеж'],
  },
  {
    id: 'croissant',
    name: 'Кроасан',
    nameEn: 'Croissant',
    description: 'Масленo, многолистово тесто. Хрупкав отвън, мек отвътре. Бадемов крем.',
    price: 4.5,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80',
    tags: ['печено', 'масленo'],
  },
  {
    id: 'chocolate-cake',
    name: 'Шоколадова Торта',
    nameEn: 'Chocolate Cake',
    description: '72% тъмен шоколад, ганаш и карамелен мус. Интензивно и богато.',
    price: 7.5,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80',
    tags: ['шоколад', 'декадентско'],
  },
  // Breakfast
  {
    id: 'avocado-toast',
    name: 'Авокадо Тост',
    nameEn: 'Avocado Toast',
    description: 'Хлебче на закваска, смачкано авокадо, яйца по пашвански, семена и микрозелени.',
    price: 9.5,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=600&q=80',
    featured: true,
    tags: ['здравословно', 'популярно'],
  },
  {
    id: 'granola-bowl',
    name: 'Гранола Бол',
    nameEn: 'Granola Bowl',
    description: 'Домашна гранола с гръцко кисело мляко, пресни плодове и мед.',
    price: 8.0,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=600&q=80',
    tags: ['здравословно', 'лек'],
  },
  {
    id: 'eggs-benedict',
    name: 'Яйца Бенедикт',
    nameEn: 'Eggs Benedict',
    description: 'Яйца по пашвански върху английски мъфин с холандски сос и прошуто.',
    price: 11.5,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&q=80',
    tags: ['ситно', 'класика'],
  },
  // Pizza
  {
    id: 'pizza-margherita',
    name: 'Маргарита',
    nameEn: 'Margherita',
    description: 'Доматен сос, моцарела fior di latte, пресен босилек и зехтин. Класиката в перфектна форма.',
    price: 14.0,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80',
    featured: true,
    tags: ['класика', 'вегетарианска'],
  },
  {
    id: 'pizza-prosciutto',
    name: 'Прошуто е Фунги',
    nameEn: 'Prosciutto e Funghi',
    description: 'Доматен сос, моцарела, прошуто крудо и пресни гъби. Деликатно и ароматно.',
    price: 17.0,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80',
    tags: ['месо', 'популярна'],
  },
  {
    id: 'pizza-quattro-formaggi',
    name: 'Куатро Формаджи',
    nameEn: 'Quattro Formaggi',
    description: 'Четири сирена: моцарела, горгонзола, пармезан и рикота върху бяла основа.',
    price: 16.5,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=600&q=80',
    tags: ['сирена', 'богата'],
  },
  {
    id: 'pizza-diavola',
    name: 'Диавола',
    nameEn: 'Diavola',
    description: 'Доматен сос, моцарела, пикантна салами и люти чушки. За любителите на огъня.',
    price: 16.0,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&q=80',
    tags: ['пикантна', 'месо'],
  },
  {
    id: 'pizza-vegetariana',
    name: 'Вегетариана',
    nameEn: 'Vegetariana',
    description: 'Доматен сос, моцарела, тиквички, чушки, маслини, червен лук и рукола.',
    price: 15.0,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1511689660979-10d2b1afd49d?w=600&q=80',
    tags: ['вегетарианска', 'свежа'],
  },
  {
    id: 'pizza-capricciosa',
    name: 'Капричоза',
    nameEn: 'Capricciosa',
    description: 'Доматен сос, моцарела, шунка, гъби, маслини и артишок. Щедра и вкусна.',
    price: 17.5,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80',
    tags: ['месо', 'класика'],
  },
  // Drinks
  {
    id: 'coca-cola',
    name: 'Кока-Кола',
    nameEn: 'Coca-Cola',
    description: 'Класическата газирана напитка. Сервира се с лед и лимон. 330мл.',
    price: 3.0,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=600&q=80',
    tags: ['газирана', 'класика'],
  },
  {
    id: 'fresh-orange',
    name: 'Пресен Портокалов Сок',
    nameEn: 'Fresh Orange Juice',
    description: 'Изцеден в момента от пресни портокали. Без добавена захар. 300мл.',
    price: 5.5,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&q=80',
    featured: true,
    tags: ['пресен', 'здравословно'],
  },
  {
    id: 'lemonade',
    name: 'Домашна Лимонада',
    nameEn: 'Homemade Lemonade',
    description: 'Лимони, мента, мед и газирана вода. Освежаваща и натурална. 400мл.',
    price: 5.0,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=600&q=80',
    tags: ['домашна', 'освежаваща'],
  },
  {
    id: 'ice-tea',
    name: 'Студен Чай с Праскова',
    nameEn: 'Peach Iced Tea',
    description: 'Черен чай, сироп от праскова, лимон и лед. Натурално и без оцветители. 400мл.',
    price: 4.5,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80',
    tags: ['студено', 'плодов'],
  },
  {
    id: 'mineral-water',
    name: 'Минерална Вода',
    nameEn: 'Mineral Water',
    description: 'Натурална минерална вода. Газирана или негазирана. 500мл.',
    price: 2.5,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1559839914-17aae19cec71?w=600&q=80',
    tags: ['вода', 'натурална'],
  },
  {
    id: 'smoothie-berry',
    name: 'Смути Горски Плодове',
    nameEn: 'Berry Smoothie',
    description: 'Боровинки, малини, банан, гръцко кисело мляко и мед. Плътен и витаминозен. 350мл.',
    price: 7.0,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=600&q=80',
    tags: ['смути', 'здравословно'],
  },
];

export const WORKING_HOURS: WorkingHours[] = [
  { day: 'Понеделник', open: '07:30', close: '21:00' },
  { day: 'Вторник', open: '07:30', close: '21:00' },
  { day: 'Сряда', open: '07:30', close: '21:00' },
  { day: 'Четвъртък', open: '07:30', close: '21:00' },
  { day: 'Петък', open: '07:30', close: '22:00' },
  { day: 'Събота', open: '08:00', close: '22:00' },
  { day: 'Неделя', open: '09:00', close: '20:00' },
];

export const CONTACT_INFO = {
  address: 'ул. Христо Ботев 14, Козлодуй 3320',
  phone: '+359 893 123 456',
  email: 'hello@delgado-cafe.bg',
  instagram: '@delgado.cafe',
  lat: 43.7808,
  lng: 23.7234,
};
